### ISSUE TITLE
我有一个好的想法：输入法应用于语言学习，发音纠正

### ISSUE THREAD

**Issue by Pantyhose-X** [RimoChan/rime-unvcode#2]
你好：你可以基于[启程输入法](https://soime.cn/) 
启程输入法只能，朗读中文，
或者基于[nvda](https://github.com/nvaccess/nvda)

启程输入法. 应用于语言学习。发音纠正，这样可以纠正发音和加深记忆，
母语不是英语。需要学习英语，市场非常大 

你可以基于[nvda](https://github.com/nvaccess/nvda)
* 关闭屏幕阅读器关闭所有其他语音提示。
* 独立使用键盘阅读器，只朗读我在键盘上输入的内容

## 额外信息

开源 TTS
[Mozilla 的 Text-to-Speech](https://github.com/mozilla/TTS)
[coqui-ai TTS](https://github.com/coqui-ai/TTS)

**Comment by RimoChan** [comment]
你是不是发错地方了？？？
